
name: ShowTime Kernel Compiler

on:
  workflow_dispatch:
    inputs:
      target_device:
        description: 'Выберите модель для сборки'
        required: true
        default: 'z3s'
        type: choice
        options:
          - z3s
          - r8s
          - c1s
          - x1s

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools ccache bc bison flex libelf-dev libssl-dev make clang lld

      - name: Build Kernel
        run: |
          chmod +x ./build.sh
          ./build.sh -m ${{ github.event.inputs.target_device }} -k y

      - name: Find built zips
        id: find_zips
        run: |
          ZIP_FILES=$(find . -type f -name "*.zip")
          if [[ -z "$ZIP_FILES" ]]; then
            echo "No ZIPs found! Exiting."
            exit 1
          fi
          echo "ZIP_FILES<<EOF" >> $GITHUB_ENV
          echo "$ZIP_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload built kernels
        uses: actions/upload-artifact@v4
        with:
          name: ShowTime-Kernel-${{ github.event.inputs.target_device }}
          path: ${{ env.ZIP_FILES }}
